import = [
  # "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/rose-pine-moon.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding = { x = 10, y = 10 }
dynamic_title = false

[font]
normal = { family = "Cousine Nerd Font Mono", style = "Regular" }

